# This is the configuration used to check the rubocop source code.

require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/CommentIndentation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 80
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'config/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/InclusiveLanguage:
  FlaggedTerms:
    offence:
      Suggestions:
        - offense

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*.rb'

Rake/Desc:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should # Custom

RSpec/ImplicitSubject:
  EnforcedStyle: single_line_only # Default

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolArray:
  Exclude:
    - 'config/routes.rb'
    - 'app/controllers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
